version: '3.9'

services:
  db:
    image: mariadb:10.5.22
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass

  wordpress:
    container_name: silmo-wp
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./html:/var/www/html #wordpressファイル群格納用
      - ./wp-content:/var/www/html/wp-content #テーマ、プラグイン開発用
      - ./silmo:/var/www/html/wp-content/themes/silmo 
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root-pass
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8888:80"
  # sqlファイルインポート時はファイルサイズの上限を変更するためコメントアウトを外す
  # volumes:
  #    - ./phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini

volumes:
    db_data: {}
